spring:
  application:
    name: kanban

  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:file:~/kanban-db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: info
    ge.edu.sangu.kanban: debug

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: log/kanban.log

  logback:
    rollingpolicy:
      file-name-pattern: log/app-%d{yyyy-MM-dd}.%i.log
      max-history: 30
